name = "clinicon-stellenplan"
main = "worker/index.js"
compatibility_date = "2026-01-23"

[[d1_databases]]
binding = "DB"
database_name = "clinicon_stellenplan"
database_id = "e58d7dc0-29f9-4289-b5a2-236717073c0b"
migrations_dir = "worker/migrations"
